receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "localhost:4317"
      http:
        endpoint: "localhost:4318"
  jaeger:
    protocols:
      grpc:
        endpoint: "localhost:14250"

exporters:
  jaeger:
    endpoint: "localhost:14250"
  logging:
    loglevel: debug

processors:
  batch:
  queued_retry:

service:
  pipelines:
    traces:
      receivers: [otlp, jaeger]
      processors: [batch, queued_retry]
      exporters: [jaeger, logging]
