version: '3'
services:
  # Jaegerの設定
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

  # サービス1の設定
  service1:
    build: ./service1  # service1のDockerfileがあるディレクトリ
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831

  # サービス2の設定
  service2:
    build: ./service2  # service2のDockerfileがあるディレクトリ
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
